Dev utm
uoft-networking/tools pull request #7
Opened 2022-12-27 17:06 UTC by Kyle-Fozo

uoft-phpipam created, uoft-snipeit updated.

-phpIPAM API and CLI tool created.
-Minor addition of location_id and asset_id lookup to snipeIT.
-snipeIT updated to support ansible workflow in phpIPAM.

2022-12-27 17:07 UTC, Kyle-Fozo commented
@alextremblay over to you, sir.

2022-12-27 18:09 UTC, alextremblay requested changes

2023-01-02 15:47 UTC, Kyle-Fozo commented
This has been done as requested, thanks.

2023-01-02 15:50 UTC, Kyle-Fozo commented on projects/phpipam/README.md
> +Configuration Options:
This has been done as requested, thanks.

2023-01-02 15:51 UTC, alextremblay approved these changes
LGTM

2023-01-02 15:52 UTC, merged